import './globals.css'
import { Red_Hat_Display } from 'next/font/google'
import React from 'react'

const rhd = Red_Hat_Display({ 
  weight: ['500', '700', '900'],
  subsets: ['latin'] ,
  display: 'swap',
  variable: '--font-RHD'
})

export const metadata = {
  title: 'Project 3',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={rhd.className}>{children}</body>
    </html>
  )
}
